// Generated by scripts/audit.mjs. Do not edit by hand.
// Every number here comes from a real run against a running server.

export interface AuditCell {
  route: string;
  theme: "dark" | "light";
  checks: number;
  violations: number;
  blocking: number;
}

export const audit = {
  captured: "2026-09-13",
  commit: "da0c161",
  axeVersion: "4.13.0",
  standard: "WCAG 2.2 AA",
  routes: ["/","/about","/projects","/skills","/experience","/resume","/contact"],
  themes: ["dark","light"],
  checks: 332,
  blocking: 0,
  violationNodes: 0,
  e2e: {"passed":37,"skipped":7,"failed":0},
  cells: [
    {
      "route": "/",
      "theme": "dark",
      "checks": 26,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/about",
      "theme": "dark",
      "checks": 24,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/projects",
      "theme": "dark",
      "checks": 23,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/skills",
      "theme": "dark",
      "checks": 23,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/experience",
      "theme": "dark",
      "checks": 22,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/resume",
      "theme": "dark",
      "checks": 22,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/contact",
      "theme": "dark",
      "checks": 26,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/",
      "theme": "light",
      "checks": 26,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/about",
      "theme": "light",
      "checks": 24,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/projects",
      "theme": "light",
      "checks": 23,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/skills",
      "theme": "light",
      "checks": 23,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/experience",
      "theme": "light",
      "checks": 22,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/resume",
      "theme": "light",
      "checks": 22,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    },
    {
      "route": "/contact",
      "theme": "light",
      "checks": 26,
      "violations": 0,
      "blocking": 0,
      "nodes": 0
    }
  ],
} as const;
