import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    slug: "ecommerce-web-application",
    name: "E-Commerce Web Application",
    applicationType: "Web Application",
    summary:
      "End-to-end QA for a consumer e-commerce storefront: authentication, catalog, cart, and checkout.",
    description:
      "A mid-size e-commerce platform serving retail customers. My QA scope covered the customer-facing storefront and the public product API. I designed and executed functional, regression, smoke, and negative test suites, then built a Playwright automation layer for the highest-risk flows.",
    categories: [
      "Manual Testing",
      "Automation",
      "API Testing",
      "Web Testing",
    ],
    testingScope: [
      "Authentication",
      "Product catalog",
      "Cart",
      "Checkout",
      "Order confirmation",
      "Product API",
    ],
    testingTypes: [
      "Functional",
      "Regression",
      "Smoke",
      "Negative",
      "Boundary",
      "API",
      "UI Automation",
    ],
    tools: ["Playwright", "Postman", "SQL", "GitHub Actions", "Jira"],
    metrics: {
      testCases: 47,
      automated: 32,
      defects: 8,
      criticalDefects: 2,
      passRate: 91,
      automationCoverage: 68,
    },
    status: "Complete",
    demo: true,
    featured: true,
    duration: "6 weeks",
    role: "QA / Automation Engineer",
    environment: "Chrome, Edge, Firefox / Windows & macOS",
    inScope: [
      "Authentication flows",
      "Product browsing and search",
      "Cart operations",
      "Checkout and payment entry",
      "Order confirmation",
      "Product API endpoints",
    ],
    outOfScope: [
      "Payment provider internal processing",
      "Inventory/warehouse backend",
      "Infrastructure and deployment",
    ],
    strategy: [
      "Risk-based test prioritisation, focusing on payment and checkout as P0.",
      "Manual exploratory testing in parallel with scripted functional cases.",
      "API validation for all public product endpoints.",
      "UI automation for high-risk, high-frequency regression flows.",
    ],
    scenarios: [
      "Register and log in with valid credentials",
      "Log in with invalid password",
      "Empty password validation",
      "Browse product catalog and apply filters",
      "Add multiple items to cart",
      "Update item quantity in cart",
      "Checkout with expired card",
      "Checkout with valid card and confirm order",
      "Fetch product list via API",
      "Retrieve single product via API",
    ],
    testCases: [
      {
        id: "TC-001",
        title: "Login with valid credentials",
        type: "Functional",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "User is redirected to the dashboard",
        executionTimeMs: 1800,
      },
      {
        id: "TC-002",
        title: "Login with invalid password",
        type: "Negative",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "Error message shown, no session created",
        executionTimeMs: 900,
      },
      {
        id: "TC-003",
        title: "Empty password validation",
        type: "Negative",
        status: "Passed",
        project: "E-Commerce",
        priority: "P1",
        expected: "Field-level validation message displayed",
        executionTimeMs: 700,
      },
      {
        id: "TC-004",
        title: "Add item to cart",
        type: "Functional",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "Item appears in cart with correct quantity",
        executionTimeMs: 1400,
      },
      {
        id: "TC-005",
        title: "Checkout with expired card",
        type: "Negative",
        status: "Failed",
        project: "E-Commerce",
        priority: "P0",
        expected: "Payment is rejected with a clear error",
        executionTimeMs: 2400,
      },
      {
        id: "TC-006",
        title: "Checkout with valid card",
        type: "Functional",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "Order is created and confirmation shown",
        executionTimeMs: 2900,
      },
      {
        id: "TC-007",
        title: "Update cart quantity",
        type: "Functional",
        status: "Passed",
        project: "E-Commerce",
        priority: "P1",
        expected: "Subtotal recalculates correctly",
        executionTimeMs: 1200,
      },
      {
        id: "TC-008",
        title: "Boundary: max cart quantity",
        type: "Boundary",
        status: "Blocked",
        project: "E-Commerce",
        priority: "P2",
        expected: "Quantity capped at configured maximum",
        executionTimeMs: 900,
      },
      {
        id: "TC-009",
        title: "API: fetch product list",
        type: "API",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "200 with paginated product payload",
        executionTimeMs: 600,
      },
      {
        id: "TC-010",
        title: "Smoke: homepage loads",
        type: "Smoke",
        status: "Passed",
        project: "E-Commerce",
        priority: "P0",
        expected: "Homepage renders with no console errors",
        executionTimeMs: 1100,
      },
    ],
    bugs: [
      {
        id: "BUG-014",
        summary: "Checkout accepts expired card",
        severity: "High",
        priority: "P0",
        status: "Fixed",
        environment: "Chrome 151 / Windows",
        module: "Checkout",
        project: "E-Commerce",
        steps: [
          "Open checkout",
          "Enter an expired card number",
          "Submit payment",
        ],
        expected: "Payment is rejected with a clear error message",
        actual: "Payment is accepted and an order is created",
        preconditions: "A user is logged in with items in cart",
        rootCause:
          "Client-side expiry check only; server did not re-validate card expiry",
        regressionResult: "Re-tested on next release, now rejected correctly",
      },
      {
        id: "BUG-009",
        summary: "Cart quantity allows negative value",
        severity: "High",
        priority: "P1",
        status: "Fixed",
        environment: "Firefox 130 / macOS",
        module: "Cart",
        project: "E-Commerce",
        steps: ["Open cart", "Decrement quantity below 1"],
        expected: "Quantity is clamped to minimum of 1",
        actual: "Quantity becomes negative, subtotal shows negative value",
        rootCause: "Missing lower-bound validation on quantity input",
        regressionResult: "Re-tested, quantity now clamps to 1",
      },
      {
        id: "BUG-011",
        summary: "Product search ignores whitespace-only query",
        severity: "Medium",
        priority: "P2",
        status: "Fixed",
        environment: "Edge 131 / Windows",
        module: "Catalog",
        project: "E-Commerce",
        steps: ["Open search", "Type spaces only", "Press Enter"],
        expected: "No results or a validation prompt",
        actual: "Server returns full catalog",
        rootCause: "Query not trimmed before searching",
      },
    ],
    automationArchitecture: [
      "Tests",
      "Page Objects",
      "Fixtures",
      "Assertions",
      "HTML Report",
      "CI Pipeline",
    ],
    lessons: [
      "Server-side validation must not be assumed from client-side checks.",
      "Risk-based prioritisation catches the most impactful defects first.",
      "Separating page objects from test logic keeps the suite maintainable.",
    ],
    improvements: [
      "Increase automation coverage of checkout flows.",
      "Add visual regression for the catalog grid.",
      "Introduce API contract tests with schema validation.",
    ],
  },
  {
    slug: "saas-billing-dashboard",
    name: "SaaS Billing & Dashboard",
    applicationType: "Web Application",
    summary:
      "QA of a subscription dashboard covering auth, plans, usage reporting, and the billing API.",
    description:
      "A subscription analytics dashboard used by internal teams. I validated authentication, plan configuration, usage reporting, and the billing API, and built an automated regression suite to guard the subscription billing flows.",
    categories: ["Manual Testing", "Automation", "API Testing", "Web Testing"],
    testingScope: [
      "Authentication",
      "Plan selection",
      "Usage reporting",
      "Billing API",
      "Role permissions",
    ],
    testingTypes: [
      "Functional",
      "Regression",
      "Negative",
      "API",
      "UI Automation",
    ],
    tools: ["Cypress", "Postman", "SQL Server", "Jira"],
    metrics: {
      testCases: 38,
      automated: 21,
      defects: 5,
      criticalDefects: 1,
      passRate: 94,
      automationCoverage: 55,
    },
    status: "Complete",
    demo: true,
    duration: "4 weeks",
    role: "Manual QA",
    environment: "Chrome, Safari / macOS",
    inScope: ["Login and SSO", "Plan selection", "Usage dashboards", "Billing API"],
    outOfScope: ["Payment gateway internal", "Infrastructure"],
    strategy: [
      "Functional testing of all role permissions.",
      "API testing of billing endpoints with schema assertions.",
      "Regression suite focused on subscription state changes.",
    ],
    scenarios: [
      "Log in via SSO",
      "Downgrade plan with active usage",
      "View usage report for current period",
      "Fetch invoice via API",
      "Access restricted page without permission",
    ],
    testCases: [
      {
        id: "TC-101",
        title: "SSO login",
        type: "Functional",
        status: "Passed",
        project: "SaaS Dashboard",
        priority: "P0",
        expected: "User authenticated and redirected",
        executionTimeMs: 1600,
      },
      {
        id: "TC-102",
        title: "Downgrade plan with active usage",
        type: "Functional",
        status: "Passed",
        project: "SaaS Dashboard",
        priority: "P0",
        expected: "Downgrade blocked or warned clearly",
        executionTimeMs: 2200,
      },
      {
        id: "TC-103",
        title: "Restricted page without permission",
        type: "Negative",
        status: "Passed",
        project: "SaaS Dashboard",
        priority: "P0",
        expected: "403 / access denied screen",
        executionTimeMs: 800,
      },
      {
        id: "TC-104",
        title: "API: fetch invoice",
        type: "API",
        status: "Passed",
        project: "SaaS Dashboard",
        priority: "P1",
        expected: "200 with invoice payload",
        executionTimeMs: 500,
      },
      {
        id: "TC-105",
        title: "Usage report empty state",
        type: "Functional",
        status: "Failed",
        project: "SaaS Dashboard",
        priority: "P1",
        expected: "Friendly empty state shown",
        executionTimeMs: 1100,
      },
    ],
    bugs: [
      {
        id: "BUG-007",
        summary: "Downgrade allowed above usage limit",
        severity: "Critical",
        priority: "P0",
        status: "Fixed",
        environment: "Chrome 150 / Windows",
        module: "Billing",
        project: "SaaS Dashboard",
        steps: ["Navigate to plan settings", "Select lower plan", "Confirm"],
        expected: "Downgrade blocked when usage exceeds plan limit",
        actual: "Downgrade succeeds, usage data is lost",
        rootCause: "Usage limit not enforced on plan change",
      },
      {
        id: "BUG-005",
        summary: "Usage report shows blank state on no data",
        severity: "Medium",
        priority: "P1",
        status: "Fixed",
        environment: "Safari 18 / macOS",
        module: "Reporting",
        project: "SaaS Dashboard",
        steps: ["Open usage report for a period with no data"],
        expected: "Empty state with a guidance message",
        actual: "Blank section, no explanation",
      },
    ],
    automationArchitecture: [
      "Tests",
      "Page Objects",
      "Fixtures",
      "Assertions",
      "HTML Report",
      "CI Pipeline",
    ],
    lessons: [
      "State transitions (plan changes) deserve dedicated regression coverage.",
      "Role-based permissions must be tested as negative scenarios.",
    ],
    improvements: [
      "Automate permission matrix checks.",
      "Add contract tests for the billing API.",
    ],
  },
  {
    slug: "inventory-management",
    name: "Inventory Management System",
    applicationType: "Backend + Web",
    summary:
      "Database and API-focused QA of an inventory system covering CRUD, stock validation, and reporting.",
    description:
      "An internal inventory management system. My focus was database integrity, API CRUD operations, stock validation rules, and reporting. This project demonstrates my SQL validation and API testing approach.",
    categories: ["Manual Testing", "API Testing", "Database"],
    testingScope: [
      "Product CRUD",
      "Stock validation",
      "Reporting",
      "Inventory API",
      "Data integrity",
    ],
    testingTypes: ["Functional", "Regression", "Negative", "Boundary", "API"],
    tools: ["Postman", "MySQL", "SQL", "Jira"],
    metrics: {
      testCases: 29,
      automated: 0,
      defects: 4,
      criticalDefects: 1,
      passRate: 88,
      automationCoverage: 0,
    },
    status: "Complete",
    demo: true,
    duration: "3 weeks",
    role: "Manual QA",
    environment: "Chrome / Windows",
    inScope: ["Product CRUD", "Stock levels", "Reporting queries", "Inventory API"],
    outOfScope: ["Warehouse integration", "Procurement"],
    strategy: [
      "API testing of all CRUD endpoints.",
      "Database validation with SQL queries.",
      "Boundary testing on stock thresholds.",
    ],
    scenarios: [
      "Create a new product",
      "Update stock level below minimum threshold",
      "Delete product with existing stock",
      "Fetch stock report via API",
      "Validate data integrity after CRUD",
    ],
    testCases: [
      {
        id: "TC-201",
        title: "Create new product",
        type: "Functional",
        status: "Passed",
        project: "Inventory",
        priority: "P0",
        expected: "Product persisted with correct data",
        executionTimeMs: 1000,
      },
      {
        id: "TC-202",
        title: "Update stock below threshold",
        type: "Boundary",
        status: "Passed",
        project: "Inventory",
        priority: "P0",
        expected: "Warning flag raised, update accepted",
        executionTimeMs: 800,
      },
      {
        id: "TC-203",
        title: "Delete product with existing stock",
        type: "Negative",
        status: "Failed",
        project: "Inventory",
        priority: "P0",
        expected: "Deletion blocked while stock remains",
        executionTimeMs: 900,
      },
      {
        id: "TC-204",
        title: "API: fetch stock report",
        type: "API",
        status: "Passed",
        project: "Inventory",
        priority: "P1",
        expected: "200 with aggregated stock data",
        executionTimeMs: 700,
      },
      {
        id: "TC-205",
        title: "Data integrity after product update",
        type: "Functional",
        status: "Passed",
        project: "Inventory",
        priority: "P1",
        expected: "No orphaned or inconsistent records",
        executionTimeMs: 1300,
      },
    ],
    bugs: [
      {
        id: "BUG-003",
        summary: "Product with stock can be deleted",
        severity: "Critical",
        priority: "P0",
        status: "Fixed",
        environment: "Chrome 149 / Windows",
        module: "Inventory",
        project: "Inventory",
        steps: [
          "Create product with stock > 0",
          "Delete the product",
        ],
        expected: "Deletion blocked while stock remains",
        actual: "Product deleted, stock records orphaned",
        rootCause: "No referential check between product and stock",
      },
      {
        id: "BUG-002",
        summary: "Stock report excludes zero-stock items",
        severity: "Medium",
        priority: "P1",
        status: "Fixed",
        environment: "Chrome 149 / Windows",
        module: "Reporting",
        project: "Inventory",
        steps: ["Open stock report", "Check zero-stock products"],
        expected: "Zero-stock items listed with quantity 0",
        actual: "Zero-stock items missing from report",
        rootCause: "Report query used an inner join on stock rows",
      },
    ],
    automationArchitecture: [],
    lessons: [
      "Referential integrity is a real, testable requirement, not just a schema rule.",
      "Reporting queries need review for missing rows (inner vs left join).",
    ],
    improvements: [
      "Add automated API tests for CRUD operations.",
      "Introduce a SQL test harness for report validation.",
    ],
  },
];

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
