import type {
  ApiEndpoint,
  MethodologyStep,
  RiskItem,
  TestCase,
  TestRun,
  BugReport,
} from "@/lib/types";
import { projects } from "./projects";

export const testCases: TestCase[] = [
  ...projects.flatMap((p) => p.testCases),
  // Additional standalone demo cases for the explorer
  {
    id: "TC-301",
    title: "Password reset with valid token",
    type: "Functional",
    status: "Passed",
    project: "E-Commerce",
    priority: "P1",
    expected: "User can reset password and log in",
    executionTimeMs: 1500,
  },
  {
    id: "TC-302",
    title: "Password reset with expired token",
    type: "Negative",
    status: "Passed",
    project: "E-Commerce",
    priority: "P1",
    expected: "Token rejected with a clear error",
    executionTimeMs: 900,
  },
  {
    id: "TC-303",
    title: "Add maximum quantity to cart",
    type: "Boundary",
    status: "Passed",
    project: "E-Commerce",
    priority: "P2",
    expected: "Quantity capped at maximum allowed",
    executionTimeMs: 1000,
  },
  {
    id: "TC-304",
    title: "Search returns no results",
    type: "Functional",
    status: "Passed",
    project: "E-Commerce",
    priority: "P2",
    expected: "Empty state shown with suggestion",
    executionTimeMs: 700,
  },
  {
    id: "TC-305",
    title: "Role: viewer cannot edit settings",
    type: "Negative",
    status: "Passed",
    project: "SaaS Dashboard",
    priority: "P0",
    expected: "Save action disabled / forbidden",
    executionTimeMs: 800,
  },
  {
    id: "TC-306",
    title: "API: create product with invalid payload",
    type: "API",
    status: "Passed",
    project: "Inventory",
    priority: "P1",
    expected: "422 with field-level validation errors",
    executionTimeMs: 600,
  },
];

export const bugs: BugReport[] = [
  ...projects.flatMap((p) => p.bugs),
  {
    id: "BUG-012",
    summary: "Session not invalidated after password change",
    severity: "High",
    priority: "P1",
    status: "Open",
    environment: "Chrome 151 / Windows",
    module: "Authentication",
    project: "E-Commerce",
    steps: ["Change password in settings", "Continue using old session"],
    expected: "Old session is invalidated",
    actual: "Old session remains active",
    rootCause: "Password change does not revoke existing sessions",
  },
  {
    id: "BUG-008",
    summary: "Invoice amount does not match usage total",
    severity: "Medium",
    priority: "P1",
    status: "Fixed",
    environment: "Chrome 150 / Windows",
    module: "Billing",
    project: "SaaS Dashboard",
    steps: ["Generate invoice", "Compare against usage report"],
    expected: "Invoice matches usage total",
    actual: "Invoice under-charges by usage delta",
  },
  {
    id: "BUG-001",
    summary: "Duplicate product names allowed",
    severity: "Low",
    priority: "P2",
    status: "Open",
    environment: "Chrome 149 / Windows",
    module: "Inventory",
    project: "Inventory",
    steps: ["Create product A", "Create product A again"],
    expected: "Duplicate name rejected or warned",
    actual: "Two products with the same name created",
  },
];

export const apiEndpoints: ApiEndpoint[] = [
  {
    id: "API-001",
    method: "GET",
    path: "/api/products",
    status: 200,
    responseTimeMs: 142,
    assertions: 12,
    passed: 12,
    scenario: "Fetch paginated product list",
    project: "E-Commerce",
  },
  {
    id: "API-002",
    method: "GET",
    path: "/api/products/:id",
    status: 200,
    responseTimeMs: 96,
    assertions: 10,
    passed: 10,
    scenario: "Fetch single product",
    project: "E-Commerce",
  },
  {
    id: "API-003",
    method: "POST",
    path: "/api/auth/login",
    status: 200,
    responseTimeMs: 180,
    assertions: 8,
    passed: 8,
    scenario: "Authenticate user",
    project: "E-Commerce",
  },
  {
    id: "API-004",
    method: "GET",
    path: "/api/invoices",
    status: 200,
    responseTimeMs: 210,
    assertions: 9,
    passed: 9,
    scenario: "Fetch invoices",
    project: "SaaS Dashboard",
  },
  {
    id: "API-005",
    method: "POST",
    path: "/api/inventory/products",
    status: 201,
    responseTimeMs: 130,
    assertions: 11,
    passed: 11,
    scenario: "Create product",
    project: "Inventory",
  },
  {
    id: "API-006",
    method: "GET",
    path: "/api/inventory/reports/stock",
    status: 200,
    responseTimeMs: 240,
    assertions: 9,
    passed: 8,
    scenario: "Fetch stock report",
    project: "Inventory",
  },
];

export const testRuns: TestRun[] = [
  {
    id: "RUN-042",
    started: "18 Aug 2026 09:42",
    durationSec: 272,
    total: 128,
    passed: 119,
    failed: 6,
    skipped: 3,
    project: "E-Commerce",
  },
  {
    id: "RUN-041",
    started: "17 Aug 2026 14:10",
    durationSec: 251,
    total: 128,
    passed: 122,
    failed: 4,
    skipped: 2,
    project: "E-Commerce",
  },
  {
    id: "RUN-040",
    started: "17 Aug 2026 08:30",
    durationSec: 198,
    total: 96,
    passed: 93,
    failed: 2,
    skipped: 1,
    project: "SaaS Dashboard",
  },
  {
    id: "RUN-039",
    started: "16 Aug 2026 16:05",
    durationSec: 142,
    total: 64,
    passed: 61,
    failed: 2,
    skipped: 1,
    project: "Inventory",
  },
];

export const methodology: MethodologyStep[] = [
  {
    title: "Understand",
    description: "Requirements and acceptance criteria.",
    detail:
      "I read the requirement, clarify the acceptance criteria, and identify the business impact before writing any test.",
  },
  {
    title: "Plan",
    description: "Scope, risk, environment, and priority.",
    detail:
      "I decide what is in scope, what is high-risk, and what environment each scenario needs, so effort goes where defects are likely.",
  },
  {
    title: "Design",
    description: "Scenarios and test cases.",
    detail:
      "I turn the plan into test scenarios and test cases with clear expected results that can be verified.",
  },
  {
    title: "Execute",
    description: "Functional, regression, exploratory, API, or automation.",
    detail:
      "I run the planned tests, plus exploratory checks on the riskiest areas, and record evidence for every result.",
  },
  {
    title: "Report",
    description: "Defects and evidence.",
    detail:
      "I document defects with reproduction steps, expected vs actual, and severity so developers can act quickly.",
  },
  {
    title: "Verify",
    description: "Retest and regression.",
    detail:
      "After a fix, I re-test the defect and run regression to confirm nothing else broke.",
  },
  {
    title: "Improve",
    description: "Evaluate the quality process.",
    detail:
      "I review what slipped through and adjust the strategy, test data, or automation to prevent the same defect next time.",
  },
];

export const riskItems: RiskItem[] = [
  {
    area: "Payment",
    risk: "HIGH",
    impact: "HIGH",
    priority: "P0",
  },
  {
    area: "Authentication",
    risk: "HIGH",
    impact: "HIGH",
    priority: "P0",
  },
  {
    area: "Profile",
    risk: "MEDIUM",
    impact: "MEDIUM",
    priority: "P1",
  },
  {
    area: "Reporting",
    risk: "MEDIUM",
    impact: "MEDIUM",
    priority: "P1",
  },
  {
    area: "Notifications",
    risk: "LOW",
    impact: "LOW",
    priority: "P2",
  },
];
