"use client";

import { Check } from "lucide-react";

import { audit } from "@/content/audit";
import { useLang } from "@/components/lang-provider";

/**
 * The signature block: the site publishes its own audit report. Every figure is
 * generated by scripts/audit.mjs from a real axe run, not written by hand, and
 * the capture date and commit ship with it so the claim can be checked.
 */
export function AuditPanel() {
  const { t, lang } = useLang();
  const isId = lang === "id";

  const figures = [
    { value: String(audit.checks), label: t("audit_checks") },
    { value: String(audit.blocking), label: t("audit_blocking") },
    { value: String(audit.e2e.passed), label: t("audit_e2e") },
    { value: String(audit.themes.length), label: t("audit_themes") },
  ];

  return (
    <div data-reveal>
      <div className="measure">
        <h2 className="h2">{t("audit_title")}</h2>
        <p className="lead mt-5 text-muted-foreground">{t("audit_desc")}</p>
      </div>

      <div className="mt-12 border border-border bg-card/60">
        <dl className="grid grid-cols-2 divide-border lg:grid-cols-4 lg:divide-x">
          {figures.map((figure, i) => (
            <div
              key={figure.label}
              className={`p-6 sm:p-8 ${i < 2 ? "border-b border-border lg:border-b-0" : ""} ${
                i % 2 === 0 ? "border-r border-border lg:border-r-0" : ""
              }`}
            >
              <dd className="hero-display tabular-nums">{figure.value}</dd>
              <dt className="label mt-3 text-muted-foreground">{figure.label}</dt>
            </div>
          ))}
        </dl>

        <div className="border-t border-border p-6 sm:p-8">
          <div className="flex items-baseline justify-between gap-4">
            <p className="label text-muted-foreground">
              {isId ? "Hasil per rute" : "Result by route"}
            </p>
            <p className="label hidden text-muted-foreground sm:block">
              <span className="mr-6">{t("audit_dark")}</span>
              {t("audit_light")}
            </p>
          </div>

          <ul className="mt-4">
            {audit.routes.map((route) => {
              const cells = audit.cells.filter((c) => c.route === route);
              return (
                <li
                  key={route}
                  className="flex items-center justify-between gap-4 border-t border-border/60 py-2.5"
                >
                  <span className="mono truncate text-xs">{route}</span>
                  <span className="flex items-center gap-6">
                    {audit.themes.map((theme) => {
                      const cell = cells.find((c) => c.theme === theme);
                      const clean = (cell?.blocking ?? 1) === 0;
                      return (
                        <span
                          key={theme}
                          className="flex items-center gap-1.5 text-xs text-muted-foreground"
                        >
                          <span
                            className={
                              "flex h-4 w-4 items-center justify-center rounded-full " +
                              (clean
                                ? "bg-success/15 text-success"
                                : "bg-destructive/15 text-destructive")
                            }
                          >
                            <Check className="h-2.5 w-2.5" />
                          </span>
                          <span className="tabular-nums">{cell?.checks ?? 0}</span>
                        </span>
                      );
                    })}
                  </span>
                </li>
              );
            })}
          </ul>

          <div className="mt-6 flex flex-col gap-3 border-t border-border pt-6 sm:flex-row sm:items-center sm:justify-between">
            <p className="mono text-xs text-muted-foreground">
              {t("audit_captured")} {audit.captured} · {audit.commit} · axe-core{" "}
              {audit.axeVersion} · {audit.standard}
            </p>
            <p className="mono text-xs text-muted-foreground">
              <span className="text-foreground">{t("audit_reproduce")}</span>
              {"  "}
              {t("audit_command")}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
