/**
 * Runs the same axe audit the E2E suite runs, then writes the result to
 * content/audit.ts so the site can publish its own report instead of a claim
 * about one.
 *
 *   node scripts/audit.mjs --e2e-passed=37 --e2e-skipped=7 --e2e-failed=0
 *
 * Start a server first: npx next start -p 4321
 */
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const axeVersion = JSON.parse(
  readFileSync("node_modules/axe-core/package.json", "utf8")
).version;

const BASE = process.env.AUDIT_BASE_URL ?? "http://localhost:4321";
const ROUTES = ["/", "/about", "/projects", "/skills", "/experience", "/resume", "/contact"];
const THEMES = ["dark", "light"];
const SETTLE_MS = 2200;

const arg = (name, fallback) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? Number(hit.split("=")[1]) : fallback;
};

const e2e = {
  passed: arg("e2e-passed", 0),
  skipped: arg("e2e-skipped", 0),
  failed: arg("e2e-failed", 0),
};

const commit = execSync("git rev-parse --short HEAD").toString().trim();
const browser = await chromium.launch();
const results = [];

for (const theme of THEMES) {
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36",
  });
  await context.addInitScript((value) => {
    Object.defineProperty(navigator, "webdriver", { get: () => false, configurable: true });
    try {
      window.localStorage.setItem("theme", value);
    } catch {}
  }, theme);

  const page = await context.newPage();

  for (const route of ROUTES) {
    await page.goto(BASE + route, { waitUntil: "networkidle" });
    await page.waitForTimeout(SETTLE_MS);
    // Scroll-reveal leaves below-the-fold sections at opacity 0, and axe skips
    // hidden nodes. Settle them first, or the report audits less than the page.
    await page.evaluate(() => {
      document
        .querySelectorAll("[data-reveal],[data-rule]")
        .forEach((node) => node.classList.add("is-in"));
    });
    await page.waitForTimeout(900);
    const analysis = await new AxeBuilder({ page })
      .withTags(["wcag2a", "wcag2aa", "wcag21a", "wcag21aa", "wcag22aa"])
      .analyze();

    const blocking = analysis.violations.filter((v) =>
      ["serious", "critical"].includes(v.impact ?? "")
    );

    results.push({
      route,
      theme,
      checks: analysis.passes.length,
      violations: analysis.violations.length,
      blocking: blocking.length,
      nodes: analysis.violations.reduce((sum, v) => sum + v.nodes.length, 0),
    });
    process.stdout.write(`.${theme}${route} `);
  }
  await context.close();
}

await browser.close();

const totalBlocking = results.reduce((sum, r) => sum + r.blocking, 0);
const totalNodes = results.reduce((sum, r) => sum + r.nodes, 0);
const checks = results.reduce((sum, r) => sum + r.checks, 0);

const body = `// Generated by scripts/audit.mjs. Do not edit by hand.
// Every number here comes from a real run against a running server.

export interface AuditCell {
  route: string;
  theme: "dark" | "light";
  checks: number;
  violations: number;
  blocking: number;
}

export const audit = {
  captured: "${new Date().toISOString().slice(0, 10)}",
  commit: "${commit}",
  axeVersion: "${axeVersion}",
  standard: "WCAG 2.2 AA",
  routes: ${JSON.stringify(ROUTES)},
  themes: ${JSON.stringify(THEMES)},
  checks: ${checks},
  blocking: ${totalBlocking},
  violationNodes: ${totalNodes},
  e2e: ${JSON.stringify(e2e)},
  cells: ${JSON.stringify(results, null, 2).replace(/\n/g, "\n  ")},
} as const;
`;

writeFileSync("content/audit.ts", body);
console.log(`\n\n${results.length} cells | ${checks} checks | ${totalBlocking} blocking | ${totalNodes} nodes`);
console.log("wrote content/audit.ts");
